apiVersion: v1
kind: Service
metadata:
  name: real-time-udp-listener-service
  namespace: real-time-udp-telemetry
spec:
  type: NodePort
  ports:
    - protocol: UDP
      port: 5005
      targetPort: 5005
  selector:
     name: real-time-udp-listener
