apiVersion: v1
kind: Service
metadata:
  name: real-time-udp-listener-service
  namespace: real-time-platform
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-name: "real-time-udp-listener-nlb"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "80"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: TCP
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"  #For public subnet
spec:
  type: LoadBalancer
  ports:
    - protocol: UDP
      port: 5005
      targetPort: 5005
  selector:
     name: real-time-udp-listener
